### ISSUE TITLE
gsoc: Add meta-formula support

### ISSUE THREAD

**Issue by gigaflw** [Homebrew/gsoc#10]
Hi @MikeMcQuaid ! I am very interested in contributing to homebrew in the coming gsoc2018. Is here the right place to get in contact ?

* I have made a trivial PR in Homebrew/homebrew-core#24884. Also, I'm poking around the source code to get familiar with it these days.
* I'm now interested in Homebrew/brew#2300: add meta-formula support. Since there seems to be little progress recently, I think it is ok to select it?
* If I send my proposal draft for review, would you like to give me some feedback?

Thanks

**Comment by MikeMcQuaid** [comment]
> I have made a trivial PR in Homebrew/homebrew-core#24884. Also, I'm poking around the source code to get familiar with it these days.

Nice work, thanks for that!

> I'm now interested in Homebrew/brew#2300: add meta-formula support. Since there seems to be little progress recently, I think it is ok to select it?

Yep!

> If I send my proposal draft for review, would you like to give me some feedback?

Yes, I'd be happy to.
