### ISSUE TITLE
GSoC 2019: Optimise formula and resource download ordering

### ISSUE THREAD

**Issue by arghyatiger** [Homebrew/gsoc#12]
When brew installing multiple formulae with multiple resources the downloads do not happen all at the beginning but are interleaved through the brew install process (even with resources within a single formula). This means if a single download fails mid-way through a lengthy build process the user may not notice and have to retry again later. This should be improved so the usability of Homebrew is improved. Similarly, this project could be extended to cover caveats and warnings for formulae being output all at the end of multiple brew installs for easy reference.

**Comment by arghyatiger** [comment]
"This means if a single download fails mid-way through a lengthy build process the user may not notice and have to retry again later. This should be improved so the usability of Homebrew is improved."

I'm a newcomer to brew but I think this part of the project should be trivial. If we were to imagine a version of the existing brew that just stores any warning and error that it encounters mid way and displays it at the end, that should solve the problem of visibility of the error to the users?

**Comment by arghyatiger** [comment]
https://github.com/Homebrew/brew/issues/1666 talks of more complicated issues of the structure of
homebrew and it's current functionality.  Which would require some discussion

@MikeMcQuaid  I'd like to work on this project. Could you shed some light on how to go about this? Does homebrew plan to take part in GSoC '19? 

I've read the guidelines and I believe this is the first step toward working with Homebrew.

**Comment by MikeMcQuaid** [comment]
> [Homebrew/brew#1666](https://github.com/Homebrew/brew/issues/1666) talks of more complicated issues of the structure of
> homebrew and it's current functionality. Which would require some discussion

This is the best starting point for an implementation.

> @MikeMcQuaid I'd like to work on this project. Could you shed some light on how to go about this? Does homebrew plan to take part in GSoC '19?

Great! Please see the README on this repository for all this information. Will happily answer any more questions in this issue. Good luck!
