### ISSUE TITLE
Assigning mentors to ideas

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/gsoc#15]
We need at least one mentor to be assigned to every idea we're planning to keep this year. Please respond with what idea you're interested in mentoring. I'll update this with the list!

* @mistydemeo - Integrating [Sorbet](https://github.com/sorbet/sorbet) for types

**Comment by SMillerDev** [comment]
- @SMillerDev and @MikeMcQuaid - Integrating livecheck into the formula DSL

**Comment by GauthamGoli** [comment]
- @GauthamGoli (along with @MikeMcQuaid) - Add license metadata to Homebrew/homebrew-core formulae

**Comment by woodruffw** [comment]
@woodruffw -- Performing ELF relocations on Linux with rbelftools/patchelf.rb (#18)

**Comment by issyl0** [comment]
As of #20 I'm on the list to mentor Sorbet with Misty.

**Comment by zachauten** [comment]
I opened a PR (#25) with a proposal for automated performance tests for brew. I'd also be interested in helping out with the livecheck proposal if help is needed with that.

**Comment by Moisan** [comment]
I'd be interested to help with the livecheck proposal also.

**Comment by MikeMcQuaid** [comment]
Done!
