### ISSUE TITLE
[Prospective Applicant] Livecheck DSL for brew

### ISSUE THREAD

**Issue by nandahkrishna** [Homebrew/gsoc#27]
Hello there! I recently found the livecheck DSL issue on brew (Homebrew/brew#7027) and wanted to work on it. Just saw that it's part of this year's GSoC ideas, and thought it'd be great to give it a go.

I've previously made a couple of formulae contributions to homebrew-core, but I'm not too proficient with Ruby. Hope to learn more by working on this. If you have any suggestions or tips on how I can get started, I'd be grateful. Thanks.

**Comment by MikeMcQuaid** [comment]
Great! I'd suggest making some minor contributions to Homebrew/brew and Homebrew/homebrew-livecheck. Check out https://github.com/homebrew/brew/#contributing for tips on how to get started. Good luck!

**Comment by nandahkrishna** [comment]
Thank you @MikeMcQuaid!
