### ISSUE TITLE
[GSoC Applicant] Interested to work on "Improve integration with Homebrew Cask"

### ISSUE THREAD

**Issue by diru1100** [Homebrew/gsoc#28]
Hello all,
I am Rohit Dandamudi, currently doing my undergrad in India. Would love to work on Homebrew as part of GSoC 2020. I am interested to work on "Improve integration with Homebrew Cask" idea. and more if possible. I am really excited to work on Homebrew as I use it on a daily basis and it saves a LOT of time. Contributing to Homebrew will help me become better at installing packages and actually understand what goes behind the abstraction (magic!)

Would be a lot helpful, if anyone can tell me where to start and whom to contact about the same.
Thank you.

P.S: Also noticed that a similar work has been done on GSoC previously [here](https://summerofcode.withgoogle.com/archive/2018/projects/4514338253570048/).

**Comment by diru1100** [comment]
@MikeMcQuaid  , @chenrui333 
Can I please have an update on this.

**Comment by vidusheeamoli** [comment]
Hey @diru1100! I too am a beginner and I found the following resources quite helpful:
* https://docs.brew.sh/ -- documentation helps you get familiar with the system
* https://github.com/homebrew/brew/#contributing -- helped me find some good first issues to work on.

All the best! 😃

**Comment by diru1100** [comment]
Thanks for the links, I have already went through them. Just wanted to know if we had to resolve any specific issues based on our idea and get more clarity from the mentors. Will start working on it.

**Comment by MikeMcQuaid** [comment]
> Would be a lot helpful, if anyone can tell me where to start and whom to contact about the same.

@diru1100 Main things to read are:
- https://github.com/homebrew/gsoc
- https://github.com/blog/2312-how-to-run-a-google-summer-of-code-project-on-github 
- https://summerofcode.withgoogle.com/get-started/ 

After that, try to get started with some simple contributions through https://github.com/homebrew/brew/#contributing.

> Can I please have an update on this.

@diru1100 Please be patient when asking for help (particularly on a weekend) and give people a few days to get back to you.


> Hey @diru1100! I too am a beginner and I found the following resources quite helpful:

@vidusheeamoli That was incredible helpful, thank you!
