### ISSUE TITLE
[PROSPECTIVE APPLICANT] Improve integration with Homebrew Cask

### ISSUE THREAD

**Issue by Lord-V15** [Homebrew/gsoc#29]
I have been using HomeBrew ever since I got my MacBook. I absolutely love it. It's the most important thing to have in my terminal. As soon as I read the name, "**Homebrew**" on Google Summer of Code's website, I gasped in excitement.
I personally did wonder why `Brew cask info` and `Brew info` were different things and as soon as I opened the projects list, the _integration with Cask_ project caught my eye. 
I do need to brush up on my Ruby skills but it would be an absolute dream come true to contribute towards a major project for HomeBrew.
I really appreciate the amount of work and effort put in by the team and would be honoured if you guide me towards a successful summer of work.

**Comment by Raman-Kumar** [comment]
@Lord-V15 
Can you suggest me some docs or resources to properly understand the **codebase**
 of **Homebrew** and **contributing** to it?

**Comment by MikeMcQuaid** [comment]
Check out https://github.com/homebrew/brew/#contributing for tips on how to get started.
