### ISSUE TITLE
GSOC 2020 - Application review request

### ISSUE THREAD

**Issue by vidusheeamoli** [Homebrew/gsoc#31]
Hello there!

I have spent the past couple of days working on my proposal for `adding support for type checking using Sorbet`. I was wondering if I could send my proposal draft for a review? If yes, then can I mail it to you?
cc - @issyl0 @mistydemeo @MikeMcQuaid 

Thank you!
Vidushee Amoli

**Comment by MikeMcQuaid** [comment]
@vidusheeamoli Yup, feel free to mail me at mike@mikemcquaid.com!
