### ISSUE TITLE
Speed up `brew`

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/gsoc#43]
Running `brew` is slower than it could be. Part of this reason is that we `require` a bunch of ActiveSupport.

It would be a good project to use `brew prof` and other profiling tools to reduce the time spent to start a `brew` process.

See more details for a specific suggestion in https://github.com/Homebrew/brew/issues/10508

**Comment by mistydemeo** [comment]
I like this one. Given this is relatively open-ended, I'd like to tag this as a 350-hour project.

**Comment by osalbahr** [comment]
The bottleneck was `git` I presume? Which I think with the recent changes will speed up `brew` commands.

**Comment by SMillerDev** [comment]
The issue says:
>  Part of this reason is that we require a bunch of ActiveSupport.

So I don't think it was just git.
