### ISSUE TITLE
Replacing Google Analytics

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/gsoc#46]
Homebrew uses Google Analytics but it would ideally be replaced with something else that's fully open source and, if necessary, self-hosted.

This replacement should only use aggregate metrics to count how many installs, users, etc. we have but without being able to drill down into information about any specific user.

A time-series database like InfluxDB may be a good backend. Any additional code should be written in a language familiar with Homebrew maintainers i.e. Ruby and Bash.

**Comment by chenrui333** [comment]
For the dashboarding, we can probably consider using grafana, this is some good example that used in the CNCF community, https://k8s.devstats.cncf.io/d/12/dashboards?orgId=1&refresh=15m

**Comment by MikeMcQuaid** [comment]
@chenrui333 I don't think we want a public dashboard here, the current analytics site/API is sufficient here for now.

**Comment by mistydemeo** [comment]
I think this would be pretty popular publicly, too. I definitely agree we should go for this one. I'm going to provisionally tag it as a 350-hour project.

**Comment by haliliceylan** [comment]
Hi, Halil is here !

I want to contribute GSOC this year, I saw your project and as a daily homebrew user, I am very interested. I want to work on this issue. Where can I start?

**Comment by AJAYK-01** [comment]
Hey,

I couldn't see any mailing info on the gsoc page, hence pinging here.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/55079486/160671132-5faea139-db89-49b9-9cfc-cee5daf8f915.png">


I quite didn't understand what is meant by a trivial pull request, could you please tell me?


Also, as per the application instructions, it is mentioned to include a link to a previous PR to homebrew?
Does that mean I have to have contributed previously to be considered?

I am quite interested in this idea, as I tend to use foss alternatives wherever I can and this really caught my eye. But I am not very familiar with Ruby (but have used Github actions and some shell scripting), and the [Technologies Used](https://github.com/Homebrew/gsoc#technologies-used-and-requirements) section mentioned that previous Ruby knowledge wasn't required, which encouraged me to give this a try.

Could someone guide me with getting started?
