### ISSUE TITLE
Dependency visualization and statistics for formulae

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/gsoc#48]
## Context

Currently, we rely on the `brew tree` to display the dependency tree (in this way, we can identify the version conflict in the dependency tree), but there is no good way of showing the dependents , so this web visualization would help with this.

Another issue I hope to add the statistics into the node so that we can show the installation number per this formulae, then we can constantly update our support and improve the merge decision when merging big PRs.

**Comment by MikeMcQuaid** [comment]
> Currently, we rely on the `brew tree` to display the dependency tree (in this way, we can identify the version conflict in the dependency tree), but there is no good way of showing the dependents , so this web visualization would help with this.

`brew tree` isn't a command?

We have `brew deps` and `brew uses`: what don't they do that you are expecting?

> Another issue I hope to add the statistics into the node so that we can show the installation number per this formulae, then we can constantly update our support and improve the merge decision when merging big PRs.

We already have analytics numbers of installation numbers. What doesn't that do that you are expecting?

**Comment by SMillerDev** [comment]
> Currently, we rely on the brew tree to display the dependency tree (in this way, we can identify the version conflict in the dependency tree), but there is no good way of showing the dependents , so this web visualization would help with this.

Isn't this `brew deps --graph <formula>`?

**Comment by mistydemeo** [comment]
Yeah, I think `brew deps --graph <formula>` does this already. If you're interested specifically in trying to graph conflicts, do you think that provides what you're looking for or do you think we need to do more?

**Comment by chenrui333** [comment]
I did not know about `--graph` command before creating the new issue, that might be sufficient for now. Closing the issue.
